export const DUMMY_WAREHOUSE_DATA = [
  {
    id: '1',
    partNumber: 'AP-2024-001',
    partName: 'Alternator',
    category: 'Electrical',
    location: 'Shelf A-12',
    quantity: 45,
    unitPrice: 125.5,
    supplier: 'AutoParts Inc.',
    lastRestocked: '2024-10-10',
  },
  {
    id: '2',
    partNumber: 'AP-2024-002',
    partName: 'Brake Pads Set',
    category: 'Brakes',
    location: 'Shelf B-05',
    quantity: 120,
    unitPrice: 45.99,
    supplier: 'BrakeMaster Ltd.',
    lastRestocked: '2024-10-12',
  },
  {
    id: '3',
    partNumber: 'AP-2024-003',
    partName: 'Engine Oil Filter',
    category: 'Engine Parts',
    location: 'Shelf C-08',
    quantity: 250,
    unitPrice: 12.5,
    supplier: 'OilTech Solutions',
    lastRestocked: '2024-10-14',
  },
  {
    id: '4',
    partNumber: 'AP-2024-004',
    partName: 'Transmission Fluid',
    category: 'Transmission',
    location: 'Shelf D-03',
    quantity: 35,
    unitPrice: 28.75,
    supplier: 'FluidDynamics Co.',
    lastRestocked: '2024-10-08',
  },
  {
    id: '5',
    partNumber: 'AP-2024-005',
    partName: 'Suspension Springs',
    category: 'Suspension',
    location: 'Shelf E-15',
    quantity: 60,
    unitPrice: 89.99,
    supplier: 'SuspensionPro',
    lastRestocked: '2024-10-11',
  },
  {
    id: '6',
    partNumber: 'AP-2024-006',
    partName: 'Spark Plugs (Set of 4)',
    category: 'Engine Parts',
    location: 'Shelf A-08',
    quantity: 180,
    unitPrice: 22.0,
    supplier: 'IgnitionTech',
    lastRestocked: '2024-10-13',
  },
  {
    id: '7',
    partNumber: 'AP-2024-007',
    partName: 'Door Handle Assembly',
    category: 'Body Parts',
    location: 'Shelf F-12',
    quantity: 40,
    unitPrice: 65.5,
    supplier: 'BodyWorks Ltd.',
    lastRestocked: '2024-10-09',
  },
  {
    id: '8',
    partNumber: 'AP-2024-008',
    partName: 'Headlight Bulb (H7)',
    category: 'Electrical',
    location: 'Shelf B-02',
    quantity: 95,
    unitPrice: 18.99,
    supplier: 'LightSolutions',
    lastRestocked: '2024-10-15',
  },
  {
    id: '9',
    partNumber: 'AP-2024-009',
    partName: 'Air Filter',
    category: 'Engine Parts',
    location: 'Shelf C-10',
    quantity: 200,
    unitPrice: 15.75,
    supplier: 'AirFlow Systems',
    lastRestocked: '2024-10-14',
  },
  {
    id: '10',
    partNumber: 'AP-2024-010',
    partName: 'Seat Cover Set',
    category: 'Interior',
    location: 'Shelf G-05',
    quantity: 25,
    unitPrice: 145.0,
    supplier: 'InteriorDesigns',
    lastRestocked: '2024-10-07',
  },
];
